package com.github.jacloc.android.aocviz.viewmodel.features.solution07

import kotlin.test.Test
import kotlin.test.assertEquals

class Solution07Test {
    @Test
    fun testSolvePart1Example() {
        val solution07 = Solution07().apply {
            part1Input = """
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............
            """.trimIndent()
        }
        val result = solution07.solvePart1()
        assertEquals("21", result)
    }

    @Test
    fun testSolvePart1Actual() {
        val solution07 = Solution07()
        val result = solution07.solvePart1()
        assertEquals("1667", result)
    }
}